/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    BusinessTimeEditor: typeof import('./src/components/BusinessTimeEditor.vue')['default']
    ChiefHeader: typeof import('./src/components/ChiefHeader.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    LoginInputCard: typeof import('./src/components/LoginInputCard.vue')['default']
    MealsCard: typeof import('./src/components/MealsCard.vue')['default']
    MealsEditForm: typeof import('./src/components/form/MealsEditForm.vue')['default']
    OrderCard: typeof import('./src/components/card/orderCard.vue')['default']
    RestaurantAndMealCard: typeof import('./src/components/card/restaurantAndMealCard.vue')['default']
    RestaurantEditForm: typeof import('./src/components/form/RestaurantEditForm.vue')['default']
    RestaurantGrid: typeof import('./src/components/list/restaurantGrid.vue')['default']
    RestaurantList: typeof import('./src/components/list/restaurantList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SigninInputCard: typeof import('./src/components/SigninInputCard.vue')['default']
  }
}
