/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    BusinessTimeEditor: typeof import('./src/components/BusinessTimeEditor.vue')['default']
    BusinessTimeSelector: typeof import('./src/components/BusinessTimeSelector.vue')['default']
    ChiefHeader: typeof import('./src/components/ChiefHeader.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    LoginInputCard: typeof import('./src/components/LoginInputCard.vue')['default']
    PutPicture: typeof import('./src/components/PutPicture.vue')['default']
    RestaurantEditForm: typeof import('./src/components/form/RestaurantEditForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SigninInputCard: typeof import('./src/components/SigninInputCard.vue')['default']
  }
}
